[supervisord]
nodaemon=true

[program:synapse]
command=/start-synapse.py

[program:proxy]
command=/proxy/bin/coap-proxy --maps-dir /proxy/maps --debug-log

[program:node_exporter]
command=/bin/node_exporter --collector.disable-defaults --collector.arp --collector.netclass --collector.netdev

[program:topologiser]
command=/topologiser
